SalesWebsite/SalesWebsite.CustomerSite/Pages/Products/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SalesWebsite.CustomerSite.Services;
using SalesWebsite.CustomerSite.ViewModel;
using SalesWebsite.Shared.Constants;
using SalesWebsite.Shared.CreateRequest;

namespace SalesWebsite.CustomerSite.Pages.Products
{
    public class DetailModel : PageModel
    {
        private readonly IProductService _productService;
        private readonly IRateService _rateService;
        private readonly IConfiguration _config;
        
        
        public DetailModel(IProductService productService, IConfiguration config, IRateService rateService)
        {
            _productService = productService;
            _config = config;
            _rateService = rateService;
        }

        public ProductVm product { get; set; }

        public async Task OnGet(int id)
        {
            product = await _productService.GetProductByIdAsync(id);
            try
            {
                if (product.Rates != null)
                {
                    product.Rate = product.Rates.Average(rate => rate.NumberOfStar);
                }
            } catch(Exception ex)
            {
                product.Rate = 5;
            }
        }

        public async Task OnPostRate(int productId)
        {
            
            // get token from cookie and pass to Service to Authorized
            string userName = Request.Cookies["userName"];
            string token = Request.Cookies["token"];
            
            if(token == null)
            {
                Response.Redirect(PagesConstants.LOGIN);
            }

            string content = Request.Form["content"];
            string star = Request.Form["star"];

            int startNumber = int.Parse(star);

            RateCreateRequest rateCreateRequest = new RateCreateRequest()
            {
                UserName = userName,
                ProductId = productId,
                Content = content,
                NumberOfStar = startNumber
            };

            await _rateService.AddRateAsync(rateCreateRequest, token);
            product = await _productService.GetProductByIdAsync(productId);
            try
            {
                product.Rate = product.Rates.Average(rate => rate.NumberOfStar);
            } catch
            {
                // Catch if Product has none rates 
            }

        }
    }
}

SalesWebsite/SalesWebsite.CustomerSite/Pages/Shared/Components/ProductRates/ProductRates.cshtml
@model SalesWebsite.CustomerSite.ViewModel.ProductVm
<div class="container">

    <div class="row  d-flex justify-content-center">

        <div class="row">

            <div class="headings d-flex justify-content-between align-items-center mb-3">
                <h5>Unread comments(@Model.Rates.Count)</h5>

                <div class="buttons">

                    <span class="badge bg-white d-flex flex-row align-items-center">
                        <span class="text-primary">Comments "ON"</span>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="flexSwitchCheckChecked" checked>

                        </div>
                    </span>

                </div>

            </div>

            @foreach (var rate in Model.Rates)
            {
                <div class="card p-3">

                    <div class="d-flex justify-content-between align-items-center">

                        <div class="user d-flex flex-row align-items-center">

                            <img src="https://i.imgur.com/hczKIze.jpg" width="30" class="user-img rounded-circle mr-2">
                            <span>
                                <small class="font-weight-bold text-primary">@rate.Customer.FullName</small>

                                <small class="font-weight-bold"> @rate.Content </small>
                            </span>

                        </div>


                        <small>2 days ago</small>

                    </div>


                    <div class="action d-flex justify-content-between mt-2 align-items-center">

                        <div class="reply px-4">
                            <small>Remove</small>
                            <span class="dots"></span>
                            <small>Reply</small>
                            <span class="dots"></span>
                            <small>Translate</small>

                        </div>
                        <div class="icons align-items-center">
                            @for (var i = 0; i < rate.NumberOfStar; i++)
                            {
                                <i class="fa fa-star text-warning"></i>
                            }
                        </div>

                    </div>

                </div>

            }


        </div>

    </div>
    <br />
    <form method="post" asp-page-handler="rate" asp-route-productId="@Model.Id">
        <div class="row rate-place">
            <div class="col-6">
                <div class="input-group">
                    <textarea class="form-control" name="content" aria-label="With textarea" placeholder="Viết bình luận"></textarea>
                </div>
                <br />
                <button class="btn btn-outline-secondary" type="submit">Xác nhận</button>
            </div>
            <div class="col-6">

                <div class="rating rating2">

                    <!--
                    -->
                    <a href="#5" title="Give 5 stars" onclick="setStar(5)">★</a>
                    <!--
                    -->
                    <a href="#4" title="Give 4 stars" onclick="setStar(4)">★</a>
                    <!--
                    -->
                    <a href="#3" title="Give 3 stars" onclick="setStar(3)">★</a>
                    <!--
                    -->
                    <a href="#2" title="Give 2 stars" onclick="setStar(2)">★</a>
                    <!--
                    -->
                    <a href="#1" title="Give 1 stars" onclick="setStar(1)">★</a>
                    <input type="hidden" name="star" id="star" value="5">
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    function setStar(starNumber) {
        document.getElementById("star").value = starNumber;
        console.log(document.getElementById("star").value);
        return false;
    }
</script>